name: Testing

on:
  workflow_dispatch:

jobs:
  tag-exists:
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@v2.x
        id: get_tags
        with:
          route: GET /repos/{owner}/{repo}/git/refs/tags
          owner: cimgui
          repo: cimgui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo tag: ${{ steps.get_tags.output.*.ref }}"
      
#       - uses: mukunku/tag-exists-action@v1.0.0
#         id: checkTag
#         with: 
#           tag: '0.1.0'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
#       - if: steps.checkTag.outputs.exists == 'true'
#         run: echo This tag DOES exists
      
#       - if: steps.checkTag.outputs.exists == 'false'
#         run: echo This tag does NOT exists

